---
abstract: 'convert module name to underscore string name and underscore string name to module name'
author:
  - 'Celogeek <geistteufel@yahoo.fr>'
build_requires:
  Carp: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Scalar::Util: 0
  Test::More: 0.94
  perl: 5.004
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ModuleUnderscore
requires:
  Exporter: 0
  perl: 5.008
version: 0.1
